# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-17 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20181026_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='url',
            field=models.CharField(max_length=1024),
        ),
    ]
