# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-21 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='pwd',
            field=models.CharField(default='123456', max_length=32),
        ),
    ]
