# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-21 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_userinfo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='mobile',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
