# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-03 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20180703_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='addr',
            field=models.CharField(default='科学大道', max_length=128),
            preserve_default=False,
        ),
    ]
