# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-31 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0003_pricepolicy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricepolicy',
            options={'verbose_name_plural': '15. 价格策略'},
        ),
        migrations.AddField(
            model_name='course',
            name='period',
            field=models.PositiveIntegerField(default=7, verbose_name='建议学习周期(days)'),
        ),
        migrations.AlterUniqueTogether(
            name='pricepolicy',
            unique_together=set([('content_type', 'object_id', 'valid_period')]),
        ),
    ]
